# Generated by Django 4.2.29 on 2026-03-22 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shortcode_type', models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Lipa na M-Pesa (Buy Goods)')], max_length=20)),
                ('tier', models.CharField(choices=[('byoc', 'Bring Your Own Credentials'), ('shared', 'Shared Till')], max_length=20)),
                ('shortcode_number', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('consumer_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('consumer_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('passkey', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('initiator_name', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'shortcode_number')},
            },
        ),
    ]
