# Generated by Django 4.2.29 on 2026-03-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcode',
            options={'ordering': ['-created_at']},
        ),
    ]
