# Generated by Django 4.2.29 on 2026-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0002_alter_shortcode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcode',
            name='account_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
