# Generated by Django 4.2.29 on 2026-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0003_shortcode_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='tier',
            field=models.CharField(choices=[('byoc', 'Bring Your Own Credentials'), ('shared', 'Shared Paybill')], max_length=20),
        ),
    ]
