# Generated by Django 4.2.29 on 2026-03-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0004_alter_shortcode_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaybillShortcode',
            fields=[
            ],
            options={
                'verbose_name': 'Paybill Shortcode',
                'verbose_name_plural': 'Paybill Shortcodes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shortcodes.shortcode',),
        ),
        migrations.CreateModel(
            name='TillShortcode',
            fields=[
            ],
            options={
                'verbose_name': 'Lipa na M-Pesa Shortcode',
                'verbose_name_plural': 'Lipa na M-Pesa Shortcodes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shortcodes.shortcode',),
        ),
    ]
