# Generated by Django 4.2.29 on 2026-03-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcodes', '0005_paybillshortcode_tillshortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcode',
            name='enable_c2b_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortcode',
            name='validation_mode',
            field=models.CharField(blank=True, choices=[('pre_register', 'Pre-registered References'), ('webhook', 'Webhook (real-time)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shortcode',
            name='validation_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_references', to='shortcodes.shortcode')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('shortcode', 'reference')},
            },
        ),
    ]
