# Generated by Django 4.2.29 on 2026-03-23 00:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortcodes', '0006_shortcode_enable_c2b_validation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('c2b_paybill', 'C2B Paybill'), ('c2b_till', 'C2B Lipa na M-Pesa'), ('stk_push', 'STK Push')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('msisdn', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_reference', models.CharField(blank=True, max_length=100)),
                ('bill_ref_number', models.CharField(blank=True, max_length=100)),
                ('transaction_desc', models.TextField(blank=True)),
                ('raw_payload', models.JSONField()),
                ('transaction_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='shortcodes.shortcode')),
            ],
            options={
                'ordering': ['-transaction_time'],
                'indexes': [models.Index(fields=['shortcode', 'status'], name='transaction_shortco_c82638_idx'), models.Index(fields=['mpesa_receipt_number'], name='transaction_mpesa_r_aace8a_idx'), models.Index(fields=['msisdn'], name='transaction_msisdn_6d4bc4_idx'), models.Index(fields=['checkout_request_id'], name='transaction_checkou_9d1840_idx')],
            },
        ),
    ]
